### ISSUE TITLE
WaitBotStop not multiple running profile friendly

### ISSUE THREAD

**Issue by LauWs** [aash/HBRelog#10]
When a bot stops, any profile running WaitBotStop will stop the task and go to next one

**Comment by aash** [comment]
Tested on latest build.
Try following setup:
![untitled](https://cloud.githubusercontent.com/assets/677620/9563459/2b825814-4ea6-11e5-9519-5b847e91ec0b.png)

WaitBotStop
Login (another character on the same wow account, relogging another wow account is not supported right now)
WaitBotStop
StopHBRelogProfile

**Comment by aash** [comment]
The fix appear to work only in my environment, It is weird :unamused:. Reopening the issue until it is resolved.

**Comment by aash** [comment]
Pushed a fresh implementation of the fix. Not closing it until I recieve enough user feedback.

**Comment by aash** [comment]
Seem to be working now.
