### ISSUE TITLE
Check for error dialogs and close them

### ISSUE THREAD

**Issue by cryptiklemur** [aash/HBRelog#11]
From: https://github.com/highvoltz/HBRelog/issues/4

> Every once in awhile, wow will get a dialog that direct 3d or something could start, and then hangs the entire hbrelog process until i close the dialog. Would be nice if that got closed.
> 
> http://screencast.com/t/xDsz2d4iSFh
> 
> The error is this: https://us.battle.net/support/en/article/world-of-warcraft-was-unable-to-start-up-3d-acceleration
> 
> > World of Warcraft was unable to start up 3D acceleration. Please make sure DirectX 9.0 is installed and your video drivers are up-to-date.
> 
> Its a modal window. I have no idea how to reproduce it.
> 
> And no logs to send. Nothing is happening, its just "Waiting for wow to start"

**Comment by aash** [comment]
Fixed by 4b2f03f6aa3f531209cc28d392600ddebc8b0b85. Please check.

**Comment by aash** [comment]
Fixed by 4b2f03f6aa3f531209cc28d392600ddebc8b0b85. Please check it out.

**Comment by aash** [comment]
@aequasi Any updates? I've fixed it 11 days ago and no feedback from you, so I'm closing it.

**Comment by cryptiklemur** [comment]
Sorry, havent been able to test. I actually can't install:

```
enter Honorbuddy installation path(where honorbuddy.exe is located): C:\My\Path\To\Honorbuddy
Microsoft (R) Build Engine version 4.6.79.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/10/2015 4:10:49 PM.
Project "C:\My\Path\To\HBRelog-master\HBRelog.csproj" on node 1 (NugetRestore;Rebuild target(s)).
C:\My\Path\To\HBRelog-master\HBRelog.csproj(305,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Build.Tasks.v4.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\MSBuild\1
2.0\bin\Microsoft.Build.Tasks.v4.0.dll' or one of its dependencies. The system cannot find the file specified.
Done Building Project "C:\My\Path\To\HBRelog-master\HBRelog.csproj" (NugetRestore;Rebuild target(s)) -- FAILED.


Build FAILED.

"C:\My\Path\To\HBRelog-master\HBRelog.csproj" (NugetRestore;Rebuild target) (1) ->
(GetNuget target) ->
  C:\My\Path\To\HBRelog-master\HBRelog.csproj(305,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Build.Tasks.v4.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\MSBuild
\12.0\bin\Microsoft.Build.Tasks.v4.0.dll' or one of its dependencies. The system cannot find the file specified.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.09
Press any key to continue . . .
```

**Comment by aash** [comment]
Do you have Visual Studio? It is trying to find framework dlls in "C:\Program Files (x86)\MSBuild\12.0\bin\" which means you have Visual Studio with .NET Framework SDK.

**Comment by cryptiklemur** [comment]
Yeah, i do

**Comment by aash** [comment]
hmm, could please find the line

```
  <UsingTask TaskName="DownloadFile" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
```

and change
`Microsoft.Build.Tasks.v4.0.dll` to
`Microsoft.Build.Tasks.v12.0.dll`.

**Comment by cryptiklemur** [comment]
Ok. that worked. Gonna test it. Running into a problem with both hbrelogs now though, where it doesn't actually do the login process. It wont type the password, or select the character, or even resize the window. But once i log in and select the character, honorbuddy starts and everything

**Comment by cryptiklemur** [comment]
nvm, figured it out. Teamviewer or Overwolf

**Comment by aequasi** [comment]
It wont resize, after i click the resize button either, no errors

**Comment by aash** [comment]
Teamviewer needs additional configuration, see the instructions on the main forum thread.

P.S. Since it works I'm closing the issue.

**Comment by cryptiklemur** [comment]
Alrighty, I'll follow up with the actually issue of the thread if it pops up again

**Comment by cryptiklemur** [comment]
Can you put the forum link in the readme?
