### ISSUE TITLE
Task "Change HB Profile" doesn't change Botbase

### ISSUE THREAD

**Issue by Enf0** [aash/HBRelog#16]
Defining a botbase to change to in the "Change HB Profile" task doesn't seem to work. When the task runs and HBRelog closes and re-opens Honorbuddy, the botbase isn't changed. Seems like a bug!

**Comment by Enf0** [comment]
Actually, even defining a botbase in the profile settings under "Bot" tab doesn't seem to work either, Honorbuddy always appears to use the last used botbase when starting up.

I tried the original HBRelog and I don't experience that issue there.

**Comment by Enf0** [comment]
It seems this issue was already reported in #9. I'll try the fix. Sorry about that.

**Comment by aash** [comment]
So do you experience the problem with latest build or not?

**Comment by Enf0** [comment]
I just tried and it works as intended now! Thanks.
