### ISSUE TITLE
Honorbuddy running wrong bot

### ISSUE THREAD

**Issue by LauWs** [aash/HBRelog#9]
Honorbuddy seems to start with the last used bot, instead of using the one configured in relogger.
![1](https://cloud.githubusercontent.com/assets/11090754/9514975/94d46000-4c9e-11e5-9699-b91c07b683bc.PNG)

Logfiles:
https://www.thebuddyforum.com/attachment.php?attachmentid=185743&d=1440661052
https://www.thebuddyforum.com/attachment.php?attachmentid=185744&d=1440661052

**Comment by aash** [comment]
The fix appear to work only in my environment, It is weird :unamused:. Reopening the issue until it is resolved.

**Comment by LauWs** [comment]
So far this seems to work by me as well.
Did a full cleanse of caches and logs and redownloaded it.

I´ll test it a bit more during today and get back to you :-)

**Comment by aash** [comment]
Actually this bug was fixed by d5d971ad1cce330feffbc7d4e73e9ec9eebca217. The fix does not depend on previously unstable behavior, so I hope it is final. Closing it.

**Comment by LauWs** [comment]
Seems to be working without problems :+1:
